INSERT INTO userTable VALUES ('Andrea', '12345', 'Andrea Ramirez', '');
INSERT INTO userTable VALUES ('Roy', 'thumbnils', 'Roy Larson', 'hello there');
INSERT INTO userTable VALUES ('Felicia', '9735623', 'Felicia Herrera', 'felicia.herrera42@example.com');
INSERT INTO userTable VALUES ('Doradora', 'summers', 'Dora Webb', '');
INSERT INTO userTable VALUES ('Sue03', 'wrench', 'Sue Kuhn', '');
INSERT INTO userTable VALUES ('Jon', 'diamond', 'Jon Reynolds', 'whatsupppp');
INSERT INTO userTable VALUES ('Kristina', 'johnson1', 'Kristina Stanley', 'Computer science undergrad');
INSERT INTO userTable VALUES ('glennnn', 'cedric', 'Glen Perez', 'I love cats.');
INSERT INTO userTable VALUES ('Lesa', 'redbaron', 'Lesa Gibson', 'idk what to write here');
INSERT INTO userTable VALUES ('Brooks', 'qwert123', 'Veronica Brooks', 'I am groot');
INSERT INTO userTable VALUES ('Ellen', '208p8whi', 'Ellen Hernandez', '');
INSERT INTO userTable VALUES ('Norma0316', 'nm1946e9', 'Norma Moore', 'hello everyone');
INSERT INTO userTable VALUES ('charlottehere', '7sgf98fg', 'Charlotte Harper', 'Hmmmmmmm');
INSERT INTO userTable VALUES ('iamcharlie', '23uhgf8hs', 'Charlie Duncan', 'this is a fake profile');
INSERT INTO userTable VALUES ('jwhite', '3457ygew9', 'Joseph White', 'i am tall');
INSERT INTO userTable VALUES ('Violet', '234875', 'Violet Reynolds', 'I am good at house chores');
INSERT INTO userTable VALUES ('14david', 'w988234h2', 'David Romero', 'I am an eletrician');
INSERT INTO userTable VALUES ('Katherine', 'nananana', 'Katherine Mitchell', 'Pick meeee');
INSERT INTO userTable VALUES ('Penny', '128469', 'Penny Lewis', '');
INSERT INTO userTable VALUES ('Allen', '23twg4', 'Aubrey Allen', 'I can help you with furniture assembly.');

INSERT INTO task(title, description, task_date, start_time, end_time, location, category, post_date, creator) VALUES ('Clean my house', 'help me clean my 2 bedroom apartment', '2018-12-09', '18:00', '20:00', '4885 Rolling Green Rd', 'Home Improvement', '2018-10-03', 'Andrea');
INSERT INTO task(title, description, task_date, start_time, end_time, location, category, post_date, creator) VALUES ('Wash my car', 'help me wash my minivan', '2018-12-11', '09:00', '11:00', '4221 Ash D', 'Others', '2018-10-03', 'Felicia');
INSERT INTO task(title, description, task_date, start_time, end_time, location, category, post_date, creator) VALUES ('Assemble furniture', 'Put together the desk I bought from ikea, idk how to do it', '2018-12-30', '09:00', '12:00', '2471 University Dr', 'Furniture Assembly', '2018-10-04', 'Andrea');
INSERT INTO task(title, description, task_date, start_time, end_time, location, category, post_date, creator) VALUES ('Parcel delivery', 'Help me eliver a small parcel to my friend', '2018-12-29', '14:00', '15:00', '4524 Eagle Point Rd', 'Others', '2018-10-05', 'Kristina');
INSERT INTO task(title, description, task_date, start_time, end_time, location, category, post_date, creator) VALUES ('Help me move', 'Need someone with a van to help me move 8 boxes of stuff from Manhattan to Queens.', '2018-12-01', '14:00', '16:00', '3285 Lake Dr', 'Moving & Packing', '2018-10-06', 'Sue03');
INSERT INTO task(title, description, task_date, start_time, end_time, location, category, post_date, creator) VALUES ('Mounting a mirror', '', '2018-12-20', '10:00', '12:00', '5369 Crestview Dr', 'Mounting & Installation', '2018-10-07', 'glennnn');
INSERT INTO task(title, description, task_date, start_time, end_time, location, category, post_date, creator) VALUES ('Hang picture frames on the wall', '', '2018-12-25', '10:00', '12:00', '1799 W Dallas St', 'General Handyman', '2018-10-07', 'jwhite');
INSERT INTO task(title, description, task_date, start_time, end_time, location, category, post_date, creator) VALUES ('Vacuum my house', '', '2018-12-27', '10:00', '13:00', '4795 Mockingbird Hill', 'Home Improvement', '2018-10-08', 'jwhite');
INSERT INTO task(title, description, task_date, start_time, end_time, location, category, post_date, creator) VALUES ('Shift my sofa', 'Help me move my sofa from living room to my badroon.', '2018-12-02', '19:00', '20:00', '6104 Blossom Hill Rd', 'Heavy Lifting', '2018-10-09', '14david');
INSERT INTO task(title, description, task_date, start_time, end_time, location, category, post_date, creator) VALUES ('Clean my garden', 'clean the rubbish and rocks in my garden', '2018-12-05', '08:00', '12:00', '8180 Nowlin Rd', 'Home Improvement', '2018-10-10', 'Katherine');
INSERT INTO task(title, description, task_date, start_time, end_time, location, category, post_date, creator) VALUES ('Clean my toilet', '', '2018-12-05', '08:00', '12:00', '4 Nowlin Rd', 'Home Improvement', '2018-10-09', 'Norma0316');
INSERT INTO task(title, description, task_date, start_time, end_time, location, category, post_date, creator) VALUES ('Mount a TV', '', '2018-12-10', '09:00', '11:00', '1130 Airplane Ave', 'Mounting & Installation', '2018-10-12', 'Penny');
INSERT INTO task(title, description, task_date, start_time, end_time, location, category, post_date, creator) VALUES ('Build a bookcase for my living room', '', '2018-12-10', '10:00', '19:00', '3674 Andreas Ave', 'Furniture Assembly', '2018-10-13', 'glennnn');
INSERT INTO task(title, description, task_date, start_time, end_time, location, category, post_date, creator) VALUES ('Install shelves in the washroom', 'install 2 plastic shelves', '2018-12-12', '16:00', '18:00', '1908 Genschaw Rd', 'Furniture Assembly', '2018-10-13', 'Kristina');
INSERT INTO task(title, description, task_date, start_time, end_time, location, category, post_date, creator) VALUES ('Repair my nightstand', 'One of the drawers in my nightstand is broken, need someone to help me fix it', '2018-12-13', '12:00', '14:00', '8458 Kraft Ave', 'General Handyman', '2018-10-13', 'Jon');
INSERT INTO task(title, description, task_date, start_time, end_time, location, category, post_date, creator) VALUES ('Pick up dry cleaning', '', '2018-12-10', '13:00', '14:00', '7435 Red Saturn Dr', 'Others', '2018-10-15', 'Lesa');
INSERT INTO task(title, description, task_date, start_time, end_time, location, category, post_date, creator) VALUES ('Carpet cleaning', 'I need an experienced person to help me clean my carpets throughoutly.', '2018-12-08', '09:00', '12:00', '5582 Wayne Rd', 'Home Improvement', '2018-10-15', 'charlottehere');
INSERT INTO task(title, description, task_date, start_time, end_time, location, category, post_date, creator) VALUES ('Waitress wanted for my housewarming party', 'must have waitressing experiece, be attentive, able to work at a fast pace', '2018-12-12', '19:00', '23:00', '3174 Werth Rd', 'Others', '2018-10-16', 'Allen');
INSERT INTO task(title, description, task_date, start_time, end_time, location, category, post_date, creator) VALUES ('take packages to the post office', 'pick up three small packages from my house and go to the nearest post office to mail them', '2018-12-23', '12:00', '13:00', '5255 Homestead Rd', 'Others', '2018-10-16', 'Roy');
INSERT INTO task(title, description, task_date, start_time, end_time, location, category, post_date, creator) VALUES ('Run some simple errands', 'such as helping me buy stamps', '2018-12-20', '12:00', '14:00', '2544 Cackson St', 'Others', '2018-10-16', 'Violet');

